### ISSUE TITLE
add test

### ISSUE THREAD

**Issue by kemingy** [kemingy/falibrary#3]
Here is a list:

- [ ] `falibrary.utils.parse_path`
- [ ] `falibrary.library.Falibrary.validate`: Query, Data, Response, Exception
- [ ] `falibrary.library.Falibrary.spec`: path, schema, definition
- [x] `falibrary.library.Falibrary` update config: version, title, UI, ...

**Comment by CaptainLazarus** [comment]
I don't understand the 4th item on the list.

**Comment by kemingy** [comment]
Let me give you an example:

```py
api = Falibrary(
    title='Machine Translation',
    version='1.2.0',
    UI='swagger',
)
```

when you pass these args when init Falibrary instance, these should be updated in `Falibrary.config`. So later these can be shown in the UI.

**Comment by CaptainLazarus** [comment]
def test_config():
    test = Falibrary(
        title='Machine Translation',
        version='1.2.0',
        UI = 'swagger',
        OPENAPI_VERSION = '2.0.1'
    )

    assert test.config.UI == 'swagger' , 'UI failed to update'
    assert test.config.TITLE == 'Machine Translation' , 'Title failed to update'
    assert test.config.VERSION == '1.2.0' , 'Version failed to update'
    assert test.config.FILENAME == default_config.FILENAME , 'Filename issues'



This seems like what it should be. Since you're just asking for unit tests, this looks like this is it. Or am I doing this wrong?

**Comment by CaptainLazarus** [comment]
I just wrote a simple unit test using your example. Should I do something else?

**Comment by kemingy** [comment]
Closing this issue since all the features are supported by [spectree](https://github.com/0b01001001/spectree). This library may be archived in the future.
